Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (406, 2, 1, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_1.swf', NULL, 
    'Online Da''wah Workshop', NULL);

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (8, 2, 2, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_2.swf', NULL, 
    'Module 2 – Challenges to Successful Da''Wah', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (9, 2, 3, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_3.swf', NULL, 
    'Challenges to Successful Da''Wah', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (10, 2, 4, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_4.swf', NULL, 
    'Challenges Faced in Searching for Islam', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (11, 2, 5, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_5.swf', NULL, 
    'Stereotypes – Background Research and Scale Development.', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (12, 2, 6, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_6.swf', NULL, 
    'Stereotypes – Background Research and Scale Development.', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (13, 2, 7, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_7.swf', NULL, 
    'Stereotypes – Background Research and Scale Development.', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (14, 2, 8, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_8.swf', NULL, 
    'Stereotypes – Research Result', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (15, 2, 9, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_9.swf', NULL, 
    'Stereotypes – Muslims Are More Likely Than Christians', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (16, 2, 10, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_10.swf', NULL, 
    'Unfriendly Mosques', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (17, 2, 11, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_11.swf', NULL, 
    'Distortions of Islam by the Media and on the Internet', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (18, 2, 12, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_12.swf', NULL, 
    'Distortions of Islam by the Media and on the Internet', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (19, 2, 13, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_13.swf', NULL, 
    'The Myth of America Being Founded as a Christian Nation', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (20, 2, 14, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_14.swf', NULL, 
    'Page 14', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (21, 2, 15, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_15.swf', NULL, 
    'Page 15', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (22, 2, 16, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_16.swf', NULL, 
    'Page 16', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (23, 2, 17, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_17.swf', NULL, 
    'Page 17', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (24, 2, 18, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_18.swf', NULL, 
    'Reducing Islam to a Long -', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (25, 2, 19, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_19.swf', NULL, 
    'Reducing Islam to a Long List...', NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (26, 2, 20, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_20.swf', NULL, 
    'Additional Challenges', NULL);
 Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (500, 2, 21, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_21.swf', NULL, 
    'Forcing the Youth to be Foreigners', NULL);   
    
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (208, 2, 22, NULL, NULL, 
    NULL, 'For Americans who may be searching for Islam, which of the following is a challenge that may block their way?', 'B', 'A) An American society that emphasizes a decadent lifestyle.', 'B) Unfriendly mosques.', 
    'C) Inability to read Arabic.', 'D) The challenge of living an Islamic lifestyle.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'For Americans who may be searching for Islam', '1');
    
    
    
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (209, 2, 23, NULL, NULL, 
    NULL, 'For Americans who may be searching for Islam, which of the following is a challenge that may block their way?', 'A', 'A) Distortions of Islam by the media and on the internet.', 'B) A lack of objective books and reading material on Islam.', 
    'C) A Friday work schedule.', 'D) The relatively small size of the Muslim ummah in America.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'For Americans who may be searching for Islam', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (210, 2, 24, NULL, NULL, 
    NULL, 'Based upon the research reported in Module #2, which of the following are among the negative stereotypes about Muslims that may hinder someone from searching for Islam?', 'E', 'A) Muslims are more likely to be sexist than are Christians.', 'B) Muslims are more likely to be unforgiving than are Christians.', 
    'C) Muslims are more likely to be violent than are Christians.', 'D) Muslims are less likely to be educated than are Christians.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Based upon the research reported in Module #2', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (211, 2, 25, NULL, NULL, 
    NULL, 'Based upon the research reported in Module #2, which of the following are among the negative stereotypes about Muslims that may hinder someone from searching for Islam?', 'E', 'A) Muslims are more likely to be isolated than are Christians.', 'B) Muslims are more likely to be persecuted than are Christians.', 
    'C) Muslims are less likely to be compassionate than are Christians.', 'D) Muslims are less likely to be educated than are Christians.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Based upon the research reported in Module #2', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (212, 2, 26, NULL, NULL, 
    NULL, 'Based upon the research reported in Module #2, which of the following are among the negative stereotypes about Muslims that may hinder someone from searching for Islam?', 'E', 'A) Muslims are more likely to be vengeful than are Christians.', 'B) Muslims are less likely to be caring than are Christians.', 
    'C)  Muslims are less likely to be accepting than are Christians.', 'D) Muslims are less likely to be educated than are Christians. ', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Based upon the research reported in Module #2', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (213, 2, 27, NULL, NULL, 
    NULL, 'Based upon the research reported in Module #2, which negative stereotype about Muslims appears to be the strongest?', 'A', 'A) Muslims are sexist.', 'B) Muslims are unforgiving.', 
    'C) Muslims are vengeful.', 'D) Muslims are lacking in compassion.', 'E) Muslims are uneducated.', 'F) All of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Based upon the research reported in Module #2', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (214, 2, 28, NULL, NULL, 
    NULL, 'Unfriendly mosques are best accounted for by:', 'D', 'A) Negative stereotypes fostered by the American media.', 'B) American society''s bias against Muslims.', 
    'C) A lack of finances.', 'D) The behavior of those Muslims attending those mosques.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Unfriendly mosques are best accounted for by', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (215, 2, 29, NULL, NULL, 
    NULL, 'Unfriendly mosques are frequently characterized by:', 'E', 'A) Failure to provide a listing in the Yellow Pages.', 'B) Failure to greet visitors in a friendly, warm, and caring manner.', 
    'C) Failure to explain the prayer service to the visitor.', 'D) Failure to obtain follow-up information (name, phone number, and address) from the visitor.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Unfriendly mosques are frequently characterized by', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (216, 2, 30, NULL, NULL, 
    NULL, 'Many converts complain that the day they say shahadah they are welcomed and congratulated by many Muslims but are thereafter often ignored in the mosque. Such behavior by Muslims is indicative of:', 'C', 'A) A false perception by new converts.', 'B) The hypersensitivity of new converts.', 
    'C) An unfriendly mosque. ', 'D) The new convert''s inability to speak Arabic or Urdu.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Many converts complain that the day', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (217, 2, 31, NULL, NULL, 
    NULL, 'Among the many distortions and/or fabrications about Islam propagated by the media or over the internet is the claim that:', 'B', 'A) Self-proclaimed Muslims were involved in the attacks of 9/11. ', 'B) Allah is nothing more than an Arab moon god. ', 
    'C) Muslim women are discriminated against in some "Muslim" countries.', 'D) So-called "honor killings" occur in some "Muslim" countries.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Among the many distortions and/or fabrications about', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (218, 2, 32, NULL, NULL, 
    NULL, 'To combat media and internet distortions about Islam, we need to:', 'D', 'A) Advise people against using the internet.', 'B) Propagate our own distortions about other religions.', 
    'C) Attack the press and media as being anti-Islamic.', 'D) Develop and mass distribute a set and standardized refutation of such distortions as soon as such distortions come to our attention.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'To combat media and internet', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (219, 2, 33, NULL, NULL, 
    NULL, 'For many Americans, one of the obstacles they face on their journey to Islam is:', 'E', 'A) Realizing that they don''t need to renounce their American national identity in order to adopt an Islamic religious identity.', 'B) Giving up their former religious identity.', 
    'C) The contrast some members of the ummah make between being a Muslim and being an American.', 'D) The perception that Allah is some cult deity other than God.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'For many Americans', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (220, 2, 34, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that at the time America was founded, the number of adult Americans belonging to a church was:', 'A', 'A) Less than 15%.  ', 'B) About 25%.  ', 
    'C) About 35%.  ', 'D) About 40%. ', 'E) About 45%.  ', 'F) Just over 50%.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (221, 2, 35, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that upon becoming president: ', 'F', 'A) None of our first two presidents belonged to a church.', 'B) None of our first three presidents belonged to a church.', 
    'C) None of our first four presidents belonged to a church.', 'D) None of our first five presidents belonged to a church.', 'E) None of our first six presidents belonged to a church.', 'F) None of our first seven presidents belonged to a church.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (222, 2, 36, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that George Washington was not a Christian but was a(n):', 'B', 'A) Atheist.', 'B) Deist.', 
    'C) Unitarian.', 'D) Agnostic.', 'E) Buddhist.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (223, 2, 37, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that Thomas Jefferson was not a Christian but was a(n):', 'B', 'A) Atheist.', 'B) Deist.', 
    'C) Unitarian.', 'D) Agnostic.', 'E) Buddhist.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (224, 2, 38, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that Benjamin Franklin was not a Christian but was a(n):', 'B', 'A) Atheist.', 'B) Deist.', 
    'C) Unitarian.', 'D) Agnostic.', 'E) Buddhist.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (225, 2, 39, NULL, NULL, 
    NULL, 'In pointing out that America was not founded as a Christian nation, we can point to the fact that the statement that "the Government of the United States is not, in any sense, founded on the Christian religion" is found in the:', 'C', 'A) Constitution.', 'B) Declaration of Independence.', 
    'C) 1797 Treaty of Tripoli.', 'D) Federalist Papers.', 'E) Articles of Confederation.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'In pointing out that America was not founded', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (226, 2, 40, NULL, NULL, 
    NULL, 'About what percentage of new converts no longer are regular participants in the mosque after one year from conversion?', 'D', 'A) 23%.', 'B) 35%.', 
    'C) 47%.', 'D) 58%.', 'E) 65%.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'About what percentage of new converts no longer', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (227, 2, 41, NULL, NULL, 
    NULL, 'According to Br Jeffrey Lang, about what percentage of Muslims in America are totally alienated from their local mosques?', 'F', 'A) 30%.', 'B) 40%', 
    'C) 50%', 'D) 60%', 'E) 70%', 'F) 80%', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'According to Br Jeffrey Lang, about what percentage', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (228, 2, 42, NULL, NULL, 
    NULL, 'Many new converts to Islam face loss of:', 'A', 'A) Social support.', 'B) Financial resources.', 
    'C) Vocational advancement.', 'D) Spiritual satisfaction.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Many new converts to Islam face loss of', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (229, 2, 43, NULL, NULL, 
    NULL, 'To help new converts who may be disowned or rejected by their families and former friends, which of the following need to be implemented?', 'E', 'A) Local mosques need to sponsor regular  or at least biweekly social events e.g., potluck suppers and not simply educational classes.', 'B) Family-on-family socializing in which several families within the established ummah take the new convert under their wing, having him over for meals etc. on an at least weekly basis.', 
    'C) Include the new convert''s non-Muslim spouse in all social events without pressuring her to convert.', 'D) Replace the new convert''s lost social support system.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'To help new converts who may be disowned', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (230, 2, 44, NULL, NULL, 
    NULL, 'One of the things that sometimes drives new converts and the second generation of Muslims in America away from Islam is ', 'A', 'A) Focusing almost exclusively on prohibitions.', 'B) Stressing Islam''s message of love.', 
    'C) Praying five times a day.', 'D) Having to pay zakat.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'One of the things that sometimes drives new converts', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (231, 2, 45, NULL, NULL, 
    NULL, 'Telling new converts that they have to adopt Arabic/Islamic names and to start wearing non-Western clothing is one example of:', 'C', 'A) Proper instruction in Islam.', 'B) Helping the new converts to adjust.', 
    'C) How to drive them away from Islam.', 'D) Unifying the ummah.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Telling new converts that they have to adopt', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (232, 2, 46, NULL, NULL, 
    NULL, 'Which of the following are ways in which the ummah can drive Muslims and potential Muslims away from the mosque and maybe from Islam?', 'E', 'A) Criticizing a sister''s colorful dress as being unIslamic.', 'B) Telling someone that none of their prayers have ever counted because he or she is not praying correctly.', 
    'C) Verbally berating someone for sitting with the soles of his feet in the direction of qiblah.', 'D) Focusing too much are prohibitions and not enough on Islam''s positive message of love and compassion.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Which of the following are ways in which the ummah', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (233, 2, 47, NULL, NULL, 
    NULL, 'What percentage of mosques say that they are trying to preserve a unique ethnic or national heritage and thus driving away those Muslims who do not fit into that heritage?', 'C', 'A) 10%', 'B) 18%', 
    'C) 27%', 'D) 35%', 'E) 43%', 'F) Over 50%.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'What percentage of mosques say that they are trying', '1');
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (234, 2, 48, NULL, NULL, 
    NULL, 'Muslim youth raised in America are most likely to develop an American national/cultural identity, regardless of the country of origin of their parents.Pressure to get them to conform to their parents'' foreign country of origin is likely to result in: ', 'E', 'A) The youth pretending to be something they are not in front of their parents.', 'B) The youth feeling like they are in the real world only when they are not around their parents and perhaps not around Muslims in general.', 
    'C) The youth feeling like their parents are trying to impose an alien and foreign culture on them.', 'D) The youth rejecting Islam when they reject their parents'' national/cultural identity.', 'E) All of the above. ', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'Muslim youth raised in America are most likely', '1');

