INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
604, 10, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_1.swf', NULL, 'Online Da''wah Workshop', 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
601, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_2.swf'
, NULL, NULL, 0); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
113, 10, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_3.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
114, 10, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_4.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
115, 10, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_5.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
116, 10, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_6.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
117, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_7.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
118, 10, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_8.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
119, 10, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_9.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
120, 10, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_10.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
121, 10, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_11.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
122, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_12.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
123, 10, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_13.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
124, 10, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_14.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
125, 10, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_15.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
126, 10, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_16.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
127, 10, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
, CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_17.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
128, 10, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_18.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
129, 10, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_19.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
130, 10, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_20.swf', NULL, NULL, 0); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
346, 10, 21, NULL, NULL, NULL, 'In focusing on the shared ethical and spiritual teachings to be found in the Bible and in Islam '
, 'B', 'A) Simply say that many of the teachings 
are the same.', 'B) Quote from the Bible and then quote the parallel teaching from the Qur''an or ahadith. '
, 'C) Quote from the Bible and then say that Islam teaches the same thing.', 'D) Quote from the Qur''an or ahadith and then say that Judaism or Christianity teaches the same thing. '
, 'E) Simply avoid this topic.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
347, 10, 22, NULL, NULL, NULL, 'The Ten Commandments are also known as the:', 'D'
, 'A) Shema.', 'B) Golden Rule.', 'C) Lex Talionis.', 'D) Decalogue.', 'E) All of the above.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
348, 10, 23, NULL, NULL, NULL, 'Prophet Muhammad''s -pbuh- statement that "None of you will have faith until he wishes for his brother what he likes for himself" is the Islamic parallel to what Christianity calls the:'
, 'B', 'A) Shema.', 'B) Golden Rule.', 'C) Lex Talionis.', 'D) Decalogue.', 'E) All of the above.'
, 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 