Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (608, 1, 1, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_1.swf', NULL, 
    'Online Da''wah Workshop', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (1, 1, 2, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_2.swf', NULL, 
    'Online Da''wah Workshop', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (2, 1, 3, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_3.swf', NULL, 
    'The Importance of da''wah', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (3, 1, 4, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_4.swf', NULL, 
    'Lessons from the qur''an -1', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (4, 1, 5, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_5.swf', NULL, 
    'Lessons from the qur''an -2', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (5, 1, 6, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_6.swf', NULL, 
    'Lessons from the qur''an -3', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (6, 1, 7, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_7.swf', NULL, 
    'Lessons from the qur''an -3', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (7, 1, 8, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m1/m_1_page_8.swf', NULL, 
    'Lessons from the Ahadith', 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (197, 1, 9, NULL, NULL, 
    NULL, 'According to Qur''an 3:104, who are the ones who shall prosper?', 'C', 'A) Those who perform extra prayers.', 'B) Those who marry and raise pious children.', 
    'C) Those who call others to righteousness, encourage goodness, and forbid evil.', 'D) Those who read the Qur''an in Arabic.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'According to Qur''an 3:104', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (198, 1, 10, NULL, NULL, 
    NULL, 'Qur''an 41:33 asks, "And who is better in speech than he who"', 'D', 'A) Refrains from backbiting.', 'B) Speaks fluent Arabic.', 
    'C) Reads the Qur''an daily.', 'D) Invites others to believe and submit to God.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'Qur''an 41:33 asks,', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (199, 1, 11, NULL, NULL, 
    NULL, 'When addressing the People of the Book, Qur''an 3:64 told Prophet Muhammad -pbuh- to tell them:', 'F', 'A) To submit to Islamic shari''a or be damned.', 'B) To dress modestly.', 
    'C) To avoid alcohol.', 'D) To give up their own scripture.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'When addressing the People of the Book', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (200, 1, 12, NULL, NULL, 
    NULL, 'Qur''an 2:143 informs us that God has made the Muslim ummah a moderate community that we:', 'D', 'A) May avoid extremes in worship.', 'B) Assume leadership over non-Muslims.', 
    'C) May prosper.', 'D) Be a witness to humanity.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'Qur''an 2:143 informs us that God has made the Muslim..', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (201, 1, 13, NULL, NULL, 
    NULL, 'Qur''an 16:125 states that we should:', 'F', 'A) Aggressively confront and combat the belief systems of non-Muslims.', 'B) Tell non-Muslims that they are going to Hell.', 
    'C) Make non-Muslims pay the jizya.', 'D) Let non-Muslims know how stupid they are for believing as they do.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'Qur''an 16:125 states that we should', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (202, 1, 14, NULL, NULL, 
    NULL, 'In inviting others to Islam, we should:', 'E', 'A) Use wisdom.', 'B) Preach in a beautiful manner.', 
    'C) Reason with them in the best possible ways. ', 'D) Be gracious.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'In inviting others to Islam, we should', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (203, 1, 15, NULL, NULL, 
    NULL, 'Prophet Muhammad -pbuh- was told that he wouldn''t have fulfilled God''s mission for him if he didn''t: ', 'A', 'A) Proclaim the message of Islam.', 'B) Become the leader for both Muslims and non-Muslims.  ', 
    'C) Migrate to Madina.', 'D) Establish the Covenant of Madina.  ', 'E) All of the above. ', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'Prophet Muhammad -pbuh- was told that', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (204, 1, 16, NULL, NULL, 
    NULL, 'In inviting the People of the Book to Islam, we should:', 'E', 'A) Refrain from disputatious arguments.', 'B) Say that we believe in the revelation that has come down to them.', 
    'C) Acknowledge that "our God and your God is one."', 'D) State that we bow down to God. ', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'In inviting the People of the Book', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (205, 1, 17, NULL, NULL, 
    NULL, 'The Prophet -pbuh- instructed us to convey the message of the Qur''an, even if', 'B', 'A) We lack good knowledge of it.  ', 'B) It is only one verse that we convey. ', 
    'C) Others do not want to hear it.', 'D) We verbally attack others in the manner in which we convey it.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'The Prophet -pbuh- instructed us to convey', 1);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (206, 1, 18, NULL, NULL, 
    NULL, 'Before attempting to teach Islam to others, we should:', 'A', 'A) Learn the required precepts of Islam and the Qur''an.', 'B) Make wudu.', 
    'C) Say two rakat of prayer.', 'D) Be able to read and understand the Qur''an in Arabic.', 'E) All of the above.', 'F) None of the above.', '1', 
    CURDATE(), '1', CURDATE(), NULL, NULL, 
    'Before attempting to teach Islam', 1);