Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (411, 7, 1, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_1.swf', NULL, 
    'Online Da''wah Workshop', NULL);

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (161, 7, 2, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_2.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (162, 7, 3, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_3.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (163, 7, 4, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_4.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (164, 7, 5, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_5.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (165, 7, 6, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_6.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (166, 7, 7, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_7.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (167, 7, 8, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_8.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (168, 7, 9, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_9.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (169, 7, 10, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_10.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (170, 7, 11, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_11.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (171, 7, 12, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_12.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (172, 7, 13, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_13.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (173, 7, 14, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_14.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (174, 7, 15, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_15.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (175, 7, 16, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_16.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (176, 7, 17, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_17.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (177, 7, 18, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_18.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (178, 7, 19, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_19.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (179, 7, 20, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_20.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (180, 7, 21, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_21.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (181, 7, 22, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_22.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (182, 7, 23, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_23.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (183, 7, 24, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_24.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (184, 7, 25, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_25.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (185, 7, 26, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_26.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (186, 7, 27, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_27.swf', NULL, 
    NULL, NULL);


----------+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (376, 7, 28, NULL, NULL, 
    NULL, 'During the fourth decade of the Christian era, Christianity was monopolized by the church at:', 'C', 'A) Antioch.', 'B) Alexandria.', 
    'C) Jerusalem.', 'D) Constantinople.', 'E) Rome.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);

--2

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (377, 7, 29, NULL, NULL, 
    NULL, 'The early Jerusalem Church:', 'E', 'A) Was led by James and the actual disciples of Jesus -pbuh-.', 'B) Was seen to be authentically Jewish by Rabbi Gamaliel, the head of the Jewish Sanhedrin.', 
    'C) Preached its message only to Israelites.', 'D) Kept the Mosaic Law.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);

--3
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (378, 7, 30, NULL, NULL, 
    NULL, 'The theology of the early "Jewish-Christian" movements:', 'A', 'A) Denied the alleged divinity of Jesus -pbuh-. ', 'B) Centered around the Trinitarian doctrine.', 
    'C) Discarded the Mosaic Law.', 'D) Followed the teachings of Paul of Tarsus.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
    ----------4
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (379, 7, 31, NULL, NULL, 
    NULL, 'By the fifth decade of the Christian era, "Jesus Movements":', 'B', 'A) Remained solely located in Palestine.', 'B) Had arisen in Damascus and other large cities in the Middle East.', 
    'C) Still lacked an ecclesiastical hierarchy including bishops etc.', 'D) Had spread as far west as Spain.', 'E) Had spread as far east as China.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
   -------------5
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (380, 7, 32, NULL, NULL, 
    NULL, 'By the fifth and sixth decades of the Christian era, Pauline Christianity was primarily located in:', 'C', 'A) Palestine and the adjoining areas.', 'B) The western part of North Africa.', 
    'C) Asia Minor and Europe.', 'D) Ethiopia and Yemen ', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
    ----------6
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (381, 7, 33, NULL, NULL, 
    NULL, 'In comparing 1st-century Pauline Christianity and 1st-century Jewish-Christianity, Pauline Christianity:', 'B', 'A) Held fast to the Mosaic Law and Jewish-Christianity did not.', 'B) Proselytized among non-Jews and Jewish Christianity did not.', 
    'C) Was seldom if ever in conflict with Jewish-Christianity.', 'D) Included the church at Jerusalem and Jewish-Christianity did not.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
    --------7
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (382, 7, 34, NULL, NULL, 
    NULL, 'During the second century of the Christian era, Christianity was led by:', 'D', 'A) A multitude of independent bishops.', 'B) The pope as sole ruler of Christianity.', 
    'C) The church at Jerusalem as sole ruler of Christianity.', 'D) The patriarchs of Rome, Constantinople, Antioch, Jerusalem, and Alexandria.', 'E) The Protestant Reformation.  ', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
    ---------8
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (383, 7, 35, NULL, NULL, 
    NULL, 'Theological struggles within early Christianity included:', 'E', 'A) Whether or not to follow the Mosaic Law.', 'B) Whether to limit mission and ministry to Jews or not.', 
    'C) Whether or not Jesus -pbuh- was actually crucified.', 'D) Whether Jesus -pbuh- was divine, both human and divine, or human.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
    -------------9
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (384, 7, 36, NULL, NULL, 
    NULL, 'Which of the following was true of Eastern Christianity and contributed to the schism between the Western Church and the Eastern Church? ', 'D', 'A) Accepted the Filioque clause.', 'B) Defined the Trinity as three persons in one substance.', 
    'C) Accepted the doctrine of Original Sin.', 'D) Used leavened bread in the Eucharist.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (385, 7, 37, NULL, NULL, 
    NULL, 'The Filioque clause refers to:', 'A', 'A) The Holy Spirit proceeding from both the Father and the Son.', 'B) The doctrine of Original Sin.', 
    'C) Issues surrounding priestly celibacy.', 'D) Whether Greek or Latin should be used for the church service.', 'E) The primacy of the pope.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (386, 7, 38, NULL, NULL, 
    NULL, 'Conflict over who had missionary responsibilities for the Bulgars:', 'C', 'A) Followed from the doctrine of Original Sin.', 'B) Pitted the Northern Church against the Southern Church.', 
    'C) Contributed to the Photian Schism of 867.', 'D) Never occurred.', 'E) Contributed to differences in the definition of the Trinity. ', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (387, 7, 39, NULL, NULL, 
    NULL, 'The Great Schism of 1054 resulted in the final separation of Western Christianity from Eastern Christianity.Which of the following contributed to this final separation between the Western and Eastern Church?', 'E', 'A) The Eastern Church''s rejection of the Filioque clause.', 'B) The marriage of Eastern priests.', 
    'C) The pope and patriarch of Constantinople excommunicating each other.', 'D) The patriarch of Constantinople closing all Latin churches in Constantinople.', 'E) All of the above.', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (388, 7, 40, NULL, NULL, 
    NULL, 'Which of the following was a Roman Catholic belief or practice to which the Protestant Reformation objected?  ', 'B', 'A) Translation of the Bible into the common vernacular.', 'B) Intercessory prayer to the Virgin Mary and the saints.', 
    'C) The Filioque clause.', 'D) The doctrine of Original Sin.', 'E) The doctrine of the Trinity.', 'F) All of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (389, 7, 41, NULL, NULL, 
    NULL, 'Which of the following was a Roman Catholic belief or practice to which the Protestant Reformation objected? ', 'F', 'A) An elaborate system of church law.', 'B) Simony.', 
    'C) Selling indulgences.', 'D) Purgatory and limbo.', 'E) Papal infallibility.', 'F) All of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (390, 7, 42, NULL, NULL, 
    NULL, 'Which of the following beliefs characterize the Mormons  (Church of Jesus Christ of Latter-day Saints)? ', 'E', 'A) There are many gods and many universes.', 'B) All humans in this universe are the result of the god of this universe breeding with his consort to form souls.  ', 
    'C) The American Indians are descendants of Israelites that came to America circa 600 BCE.  ', 'D) Joseph Smith was a 19th-century prophet who translated some ancient golden plates that had been engraved by Mormon.  ', 'E) All of the above.  ', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (391, 7, 43, NULL, NULL, 
    NULL, 'Glossolalia refers to:', 'A', 'A) Speaking in tongues due to being infused with the Holy Spirit.', 'B) The Filioque clause.', 
    'C) The doctrine of the Trinity.', 'D) The doctrine of Original Sin.', 'E) A fundamental belief of the Roman Catholic Church.  ', 'F) None of the above.', '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (392, 7, 44, NULL, NULL, 
    NULL, 'During the early years of Christianity, each locale had its own set of scripture and doctrine, which could be quite different from those of Christianity in different locations ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (393, 7, 45, NULL, NULL, 
    NULL, 'In early Christianity, Pauline Christianity and Jewish-Christianity were the same thing', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (394, 7, 46, NULL, NULL, 
    NULL, 'Paul of Tarsus had been an intimate of Jesus -pbuh- during the latter’s earthly ministry', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (395, 7, 47, NULL, NULL, 
    NULL, 'Acts and Galatians are Pauline documents', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (396, 7, 48, NULL, NULL, 
    NULL, 'During the second century of the Christian era, the bishop and patriarch of Rome began to claim primacy over all other bishops and patriarchs, but his claim was largely ignored ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (397, 7, 49, NULL, NULL, 
    NULL, 'The Bible includes passages that show that Jesus -pbuh- upheld the Mosaic Law while Paul of Tarsus sought to abolish it ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (398, 7, 50, NULL, NULL, 
    NULL, 'With regard to the Christian doctrine of salvation, the Western Church stressed Christ''s -pbuh- alleged resurrection while the Eastern Church stressed his alleged crucifixion and suffering', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (399, 7, 51, NULL, NULL, 
    NULL, 'During the Photian Schism of 867, the pope excommunicated the patriarch of Constantinople, who in turn excommunicated the pope ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (400, 7, 52, NULL, NULL, 
    NULL, 'The Anabaptist movements within Protestant Christianity insisted on infant baptism ', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (401, 7, 53, NULL, NULL, 
    NULL, 'The Counter Reformation was a movement within Roman Catholicism that corrected the worst abuses to which the Protestants were objecting ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (402, 7, 54, NULL, NULL, 
    NULL, 'The Jehovah''s Witness believe in a literal hell', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (403, 7, 55, NULL, NULL, 
    NULL, 'The Jehovah''s Witness believe in a general resurrection in the End Times in which everyone will be resurrected', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (404, 7, 56, NULL, NULL, 
    NULL, 'Pentecostals believe in glossolalia ', 'A', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (405, 7, 57, NULL, NULL, 
    NULL, 'The concept of the Rapture traces back to 1st-century Christianity ', 'B', 'A) True', 'B) False', 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL);