INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
604, 10, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_1.swf', NULL, 'Online Da''wah Workshop', 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
601, 10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_2.swf'
, NULL, NULL, 0); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
113, 10, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_3.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
114, 10, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_4.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
115, 10, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_5.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
116, 10, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_6.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
117, 10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_7.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
118, 10, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_8.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
119, 10, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_9.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
120, 10, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_10.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
121, 10, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_11.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
122, 10, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_12.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
123, 10, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_13.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
124, 10, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6b/m_6B_page_14.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
125, 10, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_15.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
126, 10, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_16.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
127, 10, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
, CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_17.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
128, 10, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_18.swf', NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
129, 10, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_19.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
130, 10, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE()
, 'pages/secure/media/m6b/m_6B_page_20.swf', NULL, NULL, 0); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
346, 10, 21, NULL, NULL, NULL, 'In focusing on the shared ethical and spiritual teachings to be found in the Bible and in Islam '
, 'B', 'A) Simply say that many of the teachings 
are the same.', 'B) Quote from the Bible and then quote the parallel teaching from the Qur''an or ahadith. '
, 'C) Quote from the Bible and then say that Islam teaches the same thing.', 'D) Quote from the Qur''an or ahadith and then say that Judaism or Christianity teaches the same thing. '
, 'E) Simply avoid this topic.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
347, 10, 22, NULL, NULL, NULL, 'The Ten Commandments are also known as the:', 'D'
, 'A) Shema.', 'B) Golden Rule.', 'C) Lex Talionis.', 'D) Decalogue.', 'E) All of the above.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
348, 10, 23, NULL, NULL, NULL, 'Prophet Muhammad''s -pbuh- statement that "None of you will have faith until he wishes for his brother what he likes for himself" is the Islamic parallel to what Christianity calls the:'
, 'B', 'A) Shema.', 'B) Golden Rule.', 'C) Lex Talionis.', 'D) Decalogue.', 'E) All of the above.'
, 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
349, 10, 24, NULL, NULL, NULL, 'If one is to make direct comparisons between Christianity and Islam, one should compare the role of the Qur''an in Islam to the role of _____  in Christianity. '
, 'C', 'A) The Bible.', 'B) The Injil.', 'C) Jesus Christ -pbuh-.', 'D) The Apostles'' Creed.'
, 'E) The Nicene Creed.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
350, 10, 25, NULL, NULL, NULL, 'If one is to make direct comparisons between Christianity and Islam, one should compare the role of the Bible in Christianity to the role of _____ in Islam.'
, 'C', 'A) The Qur''an.', 'B) The sira.', 'C) The ahadith.', 'D) Fiqh.', 'E) Prophet Muhammad -pbuh-.'
, 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
351, 10, 26, NULL, NULL, NULL, 'One can show that it is a misconception to state that Islam is an Arab religion by noting that:'
, 'E', 'A) Many Arabs are not Muslims.', 'B) About 05% or more of Arabs in Jordan, Syria, Lebanon, and Palestine are Christians. '
, 'C) The vast majority of Muslims are not Arabs.', 'D) A majority of Muslims in America were born in America.'
, 'E) All of the above.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
352, 10, 27, NULL, NULL, NULL, 'Which of the following statements is not true?', 'A'
, 'A) Over 50% of the enslaved Africans in the American South were Muslims. ', 'B) Muslims helped to tame and settle the American Wild West.'
, 'C) Muslims fought in the Union Army during the American Civil War.', 'D) Muslims fought to secure American independence from Great Britain during the American Revolutionary War.'
, 'E) Muslims were in America with the Spanish Conquistadors in the 16th century.'
, 'F) All of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
353, 10, 28, NULL, NULL, NULL, 'In presenting the basics of Islam, which of the following is it not necessary to present?'
, 'C', 'A) An explanation of the Qur''an and sunnah.', 'B) The six pillars of faith.'
, 'C) An explanation of fiqh.', 'D) The five pillars of practice.', 'E) A very brief biography of Prophet Muhammad -pbuh-.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
354, 10, 29, NULL, NULL, NULL, 'In discussing differences between Islam and Christianity, it is important to: '
, 'F', 'A) Vigorously refute the Christian belief in the crucifixion of Jesus -pbuh-. '
, 'B) Label the doctrine of the Trinity as polytheism.', 'C) Be aggressive in one''s presentation.'
, 'D) Compare the Christian belief in Jesus -pbuh- being the begotten son of God with stories of the Greek gods coming down from Mt. Olympus and impregnating women.'
, 'E) Point out contradictions in the Bible.', 'F) Be kind, tactful, and respectful. '
, '1',  CURDATE(), '1', CURDATE()
, NULL, NULL, NULL, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
355, 10, 30, NULL, NULL, NULL, 'The major differences between Islam and Christianity concern:'
, 'F', 'A) The mission and ministry of Jesus -pbuh-.', 'B) The crucifixion event.'
, 'C) The nature of Jesus -pbuh-.', 'D) The nature of God.', 'E) The contemporary Bible as divine revelation.'
, 'F) All of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
356, 10, 31, NULL, NULL, NULL, 'Which of the following early Christian groups denied the divinity of Jesus -pbuh-?'
, 'E', 'A) The Ebionites.', 'B) Dynamic Monarchianism.', 'C) Arianism.', 'D) The Paulicians of Armenia.'
, 'E) All of the above.', 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
357, 10, 32, NULL, NULL, NULL, 'Which of the following figures in early Christianity maintained that Jesus -pbuh- was totally human, not divine? '
, 'B', 'A) Athanasius.', 'B) Paul of Samosata.', 'C) Augustine. ', 'D) Paul of Tarsus.'
, 'E) All of the above.', 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
358, 10, 33, NULL, NULL, NULL, 'Which church council said that Jesus -pbuh- was "unlike" God?'
, 'D', 'A) Council of Nicaea in 325.', 'B) Council of Constantinople in 381.', 'C) Council of Chalcedon in 451.'
, 'D) Council of Sirmium in 357.', 'E) All of the above.', 'F) None of the above.'
, '1', CURDATE(), '1', CURDATE()
, NULL, NULL, NULL, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
359, 10, 34, NULL, NULL, NULL, 'In discussing the prophethood of Muhammad -pbuh-, one should:'
, 'E', 'A) Use concrete stories.', 'B) Emphasize his love and compassion.', 'C) Be very careful not to aggrandize.'
, 'D) Use Biblical "prophecy" very cautiously, if at all.', 'E) All of the above.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
366, 10, 41, NULL, NULL, NULL, 'Both Islam and Christianity teach that upon his return to earth Jesus -pbuh- will slay the Antichrist'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
361, 10, 36, NULL, NULL, NULL, 'In terms of finding common ground between Islam and the religion of the non-Muslim listener, it is important to know the basics of the listener''s religion'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
362, 10, 37, NULL, NULL, NULL, 'One can safely assume that the Biblical stories of the prophets are the same as the stories found in the Qur''an'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 



INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
363, 10, 38, NULL, NULL, NULL, 'Stories of Abraham''s (pbuh) life in Ur (Qur''an), in Palestine (Bible), and in Makkah (Qur''an) are examples of prophetic stories from the Bible and the Qur’an that complement each other without contradicting each other.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
364, 10, 39, NULL, NULL, NULL, 'The story in the Qur''an of Jesus -pbuh- speaking in infancy is also found in the Bible'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
365, 10, 40, NULL, NULL, NULL, 'While not found in the Bible, the story in the Qur''an of Jesus -pbuh- turning clay pigeons into real birds is found in Christianity''s apocryphal gospels'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
360, 10, 35, NULL, NULL, NULL, 'In terms of da''wah content, it is important to stick strictly to a discussion of Islam and avoid a discussion of politics, whether foreign (e.g., Palestine and Kashmir) or domestic.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

