INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
605, 11, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_1.swf', NULL, 'Online Da''wah Workshop', 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
602, 11, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_2.swf'
, NULL, NULL, 0); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
131, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_3.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
132, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_4.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
133, 11, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_5.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
134, 11, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_6.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
135, 11, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_7.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
136, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_8.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
137, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_9.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
138, 11, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_10.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
139, 11, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_11.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
140, 11, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_12.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
141, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_13.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
142, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_14.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
143, 11, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_15.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
144, 11, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_16.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
145, 11, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_17.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
146, 11, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_18.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
147, 11, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_19.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
148, 11, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_20.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
149, 11, 21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_21.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
150, 11, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_22.swf', NULL, NULL, 0); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
151, 11, 23, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_23.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
152, 11, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_24.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
153, 11, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_25.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
154, 11, 26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_26.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
155, 11, 27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_27.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
156, 11, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_28.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
157, 11, 29, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_29.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
158, 11, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_30.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
159, 11, 31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_31.swf', NULL, NULL, 0);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
160, 11, 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  CURDATE(), '1', CURDATE(), 'pages/secure/media/m6c/m_6C_page_32.swf', NULL, NULL, 0); 








INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
349, 11, 24, NULL, NULL, NULL, 'If one is to make direct comparisons between Christianity and Islam, one should compare the role of the Qur''an in Islam to the role of _____  in Christianity. '
, 'C', 'A) The Bible.', 'B) The Injil.', 'C) Jesus Christ -pbuh-.', 'D) The Apostles'' Creed.'
, 'E) The Nicene Creed.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
350, 11, 25, NULL, NULL, NULL, 'If one is to make direct comparisons between Christianity and Islam, one should compare the role of the Bible in Christianity to the role of _____ in Islam.'
, 'C', 'A) The Qur''an.', 'B) The sira.', 'C) The ahadith.', 'D) Fiqh.', 'E) Prophet Muhammad -pbuh-.'
, 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
351, 11, 26, NULL, NULL, NULL, 'One can show that it is a misconception to state that Islam is an Arab religion by noting that:'
, 'E', 'A) Many Arabs are not Muslims.', 'B) About 05% or more of Arabs in Jordan, Syria, Lebanon, and Palestine are Christians. '
, 'C) The vast majority of Muslims are not Arabs.', 'D) A majority of Muslims in America were born in America.'
, 'E) All of the above.', 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
352, 11, 27, NULL, NULL, NULL, 'Which of the following statements is not true?', 'A'
, 'A) Over 50% of the enslaved Africans in the American South were Muslims. ', 'B) Muslims helped to tame and settle the American Wild West.'
, 'C) Muslims fought in the Union Army during the American Civil War.', 'D) Muslims fought to secure American independence from Great Britain during the American Revolutionary War.'
, 'E) Muslims were in America with the Spanish Conquistadors in the 16th century.'
, 'F) All of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
353, 11, 28, NULL, NULL, NULL, 'In presenting the basics of Islam, which of the following is it not necessary to present?'
, 'C', 'A) An explanation of the Qur''an and sunnah.', 'B) The six pillars of faith.'
, 'C) An explanation of fiqh.', 'D) The five pillars of practice.', 'E) A very brief biography of Prophet Muhammad -pbuh-.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
354, 11, 29, NULL, NULL, NULL, 'In discussing differences between Islam and Christianity, it is important to: '
, 'F', 'A) Vigorously refute the Christian belief in the crucifixion of Jesus -pbuh-. '
, 'B) Label the doctrine of the Trinity as polytheism.', 'C) Be aggressive in one''s presentation.'
, 'D) Compare the Christian belief in Jesus -pbuh- being the begotten son of God with stories of the Greek gods coming down from Mt. Olympus and impregnating women.'
, 'E) Point out contradictions in the Bible.', 'F) Be kind, tactful, and respectful. '
, '1',  CURDATE(), '1', CURDATE()
, NULL, NULL, NULL, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
355, 11, 30, NULL, NULL, NULL, 'The major differences between Islam and Christianity concern:'
, 'F', 'A) The mission and ministry of Jesus -pbuh-.', 'B) The crucifixion event.'
, 'C) The nature of Jesus -pbuh-.', 'D) The nature of God.', 'E) The contemporary Bible as divine revelation.'
, 'F) All of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
356, 11, 31, NULL, NULL, NULL, 'Which of the following early Christian groups denied the divinity of Jesus -pbuh-?'
, 'E', 'A) The Ebionites.', 'B) Dynamic Monarchianism.', 'C) Arianism.', 'D) The Paulicians of Armenia.'
, 'E) All of the above.', 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
357, 11, 32, NULL, NULL, NULL, 'Which of the following figures in early Christianity maintained that Jesus -pbuh- was totally human, not divine? '
, 'B', 'A) Athanasius.', 'B) Paul of Samosata.', 'C) Augustine. ', 'D) Paul of Tarsus.'
, 'E) All of the above.', 'F) None of the above.', '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
358, 11, 33, NULL, NULL, NULL, 'Which church council said that Jesus -pbuh- was "unlike" God?'
, 'D', 'A) Council of Nicaea in 325.', 'B) Council of Constantinople in 381.', 'C) Council of Chalcedon in 451.'
, 'D) Council of Sirmium in 357.', 'E) All of the above.', 'F) None of the above.'
, '1', CURDATE(), '1', CURDATE()
, NULL, NULL, NULL, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
359, 11, 34, NULL, NULL, NULL, 'In discussing the prophethood of Muhammad -pbuh-, one should:'
, 'E', 'A) Use concrete stories.', 'B) Emphasize his love and compassion.', 'C) Be very careful not to aggrandize.'
, 'D) Use Biblical "prophecy" very cautiously, if at all.', 'E) All of the above.'
, 'F) None of the above.', '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
366, 11, 41, NULL, NULL, NULL, 'Both Islam and Christianity teach that upon his return to earth Jesus -pbuh- will slay the Antichrist'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
361, 11, 36, NULL, NULL, NULL, 'In terms of finding common ground between Islam and the religion of the non-Muslim listener, it is important to know the basics of the listener''s religion'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
362, 11, 37, NULL, NULL, NULL, 'One can safely assume that the Biblical stories of the prophets are the same as the stories found in the Qur''an'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 



INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
363, 11, 38, NULL, NULL, NULL, 'Stories of Abraham''s (pbuh) life in Ur (Qur''an), in Palestine (Bible), and in Makkah (Qur''an) are examples of prophetic stories from the Bible and the Qur’an that complement each other without contradicting each other.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
364, 11, 39, NULL, NULL, NULL, 'The story in the Qur''an of Jesus -pbuh- speaking in infancy is also found in the Bible'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
365, 11, 40, NULL, NULL, NULL, 'While not found in the Bible, the story in the Qur''an of Jesus -pbuh- turning clay pigeons into real birds is found in Christianity''s apocryphal gospels'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1', CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
360, 11, 35, NULL, NULL, NULL, 'In terms of da''wah content, it is important to stick strictly to a discussion of Islam and avoid a discussion of politics, whether foreign (e.g., Palestine and Kashmir) or domestic.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 







INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
367, 11, 44, NULL, NULL, NULL, 'It is sufficient to say that the Bible and the Qur''an have many of the same ethical and spiritual teachings'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
368, 11, 33, NULL, NULL, NULL, 'A common misconception held by Muslims is that the Torah is the same as Genesis, Exodus, Numbers, Leviticus, and Deuteronomy.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL
, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
369, 11, 34, NULL, NULL, NULL, 'Muslims did not arrive in America until the 19th century'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
370, 11, 35, NULL, NULL, NULL, 'It is important to differentiate various Third World cultural practices of "Muslim" countries from Islam'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
371, 11, 36, NULL, NULL, NULL, 'In presenting the basics of Islam, it is important to keep the initial presentation simple'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
372, 11, 37, NULL, NULL, NULL, 'Most Christians have read the entire Bible', 'B', 'A) True'
, 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
373, 11, 38, NULL, NULL, NULL, 'Most Christians are quite familiar with early church history'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
374, 11, 39, NULL, NULL, NULL, 'The Jewish Talmud says that Jesus -pbuh- was crucified'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
606, 11, 40, NULL, NULL, NULL, 'The Basilideans, an early Christian sect of the 2nd century, maintained that Simon of Cyrene was crucified in place of Jesus -pbuh-'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1);

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
375, 11, 41, NULL, NULL, NULL, 'Traditional Christianity maintains that Jesus -pbuh- is God, not man'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
607, 11, 42, NULL, NULL, NULL, 'The Trinitarian position is polytheistic', 'B', 'A) True'
, 'B) False', NULL, NULL, NULL, NULL, '1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
600, 11, 43, NULL, NULL, NULL, 'When talking about Islam to a potential / new muslim you need to ', 'F', 'A) Promote your Madhab'
, 'B) Promote the Hanafi Madhab', 'C) Promote the Shafi Madhab', 'D) Promote the Maliki Madhab', 'E) Promote the Hambali Madhab', 'F) Let the new-muslim choose their own after accepting Islam', 
'1',  CURDATE(), '1', CURDATE(), NULL, NULL, NULL, 1); 