Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (615, 8, 1, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_1.swf', NULL, 
    NULL, 0);

Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (187, 8, 2, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_2.swf', NULL, 
    NULL, 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (188, 8, 3, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_3.swf', NULL, 
    NULL, 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (189, 8, 4, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_4.swf', NULL, 
    NULL, 0);
    
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (616, 8, 5, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_5.swf', NULL, 
    NULL, 0);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (617, 8, 6, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'pages/secure/media/m8/m_8_page_6.swf', NULL, 
    NULL, 0);
    
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (1002, 8,7, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    CURDATE(), '1', CURDATE(), 'dummy.swf', NULL, 
    NULL, NULL);  

