INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
605, 11, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_1.swf', NULL, 'Online Da''wah Workshop', NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
602, 11, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'pages/secure/media/m6c/m_6C_page_2.swf'
, NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
131, 11, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_3.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
132, 11, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_4.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
133, 11, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_5.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
134, 11, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_6.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
135, 11, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_7.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
136, 11, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_8.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
137, 11, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_9.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
138, 11, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_10.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
139, 11, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_11.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
140, 11, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_12.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
141, 11, 13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_13.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
142, 11, 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_14.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
143, 11, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_15.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
144, 11, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_16.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
145, 11, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_17.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
146, 11, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_18.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
147, 11, 19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_19.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
148, 11, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_20.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
149, 11, 21, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_21.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
150, 11, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_22.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
151, 11, 23, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_23.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
152, 11, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_24.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
153, 11, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_25.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
154, 11, 26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_26.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
155, 11, 27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_27.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
156, 11, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_28.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
157, 11, 29, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_29.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
158, 11, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_30.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
159, 11, 31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_31.swf', NULL, NULL, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
160, 11, 32, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1'
,  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pages/secure/media/m6c/m_6C_page_32.swf', NULL, NULL, NULL); 


INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
367, 11, 32, NULL, NULL, NULL, 'It is sufficient to say that the Bible and the Qur''an have many of the same ethical and spiritual teachings'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
368, 11, 33, NULL, NULL, NULL, 'A common misconception held by Muslims is that the Torah is the same as Genesis, Exodus, Numbers, Leviticus, and Deuteronomy.'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
369, 11, 34, NULL, NULL, NULL, 'Muslims did not arrive in America until the 19th century'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
370, 11, 35, NULL, NULL, NULL, 'It is important to differentiate various Third World cultural practices of "Muslim" countries from Islam'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
371, 11, 36, NULL, NULL, NULL, 'In presenting the basics of Islam, it is important to keep the initial presentation simple'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
372, 11, 37, NULL, NULL, NULL, 'Most Christians have read the entire Bible', 'B', 'A) True'
, 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
373, 11, 38, NULL, NULL, NULL, 'Most Christians are quite familiar with early church history'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
374, 11, 39, NULL, NULL, NULL, 'The Jewish Talmud says that Jesus -pbuh- was crucified'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
606, 11, 40, NULL, NULL, NULL, 'The Basilideans, an early Christian sect of the 2nd century, maintained that Simon of Cyrene was crucified in place of Jesus -pbuh-'
, 'A', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
375, 11, 41, NULL, NULL, NULL, 'Traditional Christianity maintains that Jesus -pbuh- is God, not man'
, 'B', 'A) True', 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 
INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
607, 11, 42, NULL, NULL, NULL, 'The Trinitarian position is polytheistic', 'B', 'A) True'
, 'B) False', NULL, NULL, NULL, NULL, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME,
VIDEO_FILE_NAME, PAGE_TITLE, ISQUESTION ) VALUES ( 
600, 11, 43, NULL, NULL, NULL, 'When talking about Islam to a potential / new muslim you need to ', 'F', 'A) Promote your Madhab'
, 'B) Promote the Hanafi Madhab', 'C) Promote the Shafi Madhab', 'D) Promote the Maliki Madhab', 'E) Promote the Hambali Madhab', 'F) Let the new-muslim choose their own after accepting Islam', '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '08/10/2009 02:02:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL); 