Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL)
 Values
   (8, 1, '1', 15, 'Module 8 - Literature for Da''wah', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m8/m_8_page_1.swf', NULL, 'Literature for Da''wah', 
    9);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (187, 8, 2, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m8/m_8_page_2.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (188, 8, 3, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m8/m_8_page_3.swf', NULL, 
    NULL, NULL);
Insert into TEST_TUTORIAL_QUESTION_ANS
   (TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID, PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, 
    PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER, QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, 
    QUESTION_OPTION_ANSWER_C, QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, 
    PAGE_TITLE, ISQUESTION)
 Values
   (189, 8, 4, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, '1', 
    TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('08/10/2009 02:02:22', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m8/m_8_page_4.swf', NULL, 
    NULL, NULL);
