INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (1, '', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'ACTIVITY_LOG', 'Mentor Request');
--Insert States--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (2, 'Austin', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'STATE', 'AS'); 
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (3, 'New York', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'STATE', 'NY');
--Insert Country --
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (4, 'Bangladesh', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'COUNTRY', 'Bangladesh');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (5, 'United States', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'COUNTRY', 'USA');
-------
--Insert Madhab--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (6, 'Hanafi', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MADHAB', 'Hanafi');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (7, 'Shafi', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MADHAB', 'Shafi');

--Insert Ethinicity--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (9, 'Asian', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'ETHINICITY', 'Asian');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (10, 'Arabian', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'ETHINICITY', 'Arabian');

--Insert Religion--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (11, 'Islam', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'RELIGION', 'Islam');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (12, 'Christian', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'RELIGION', 'Christian');

--Insert Profession--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (13, 'IT Profeesional', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'PROFESSION', 'IT Profeesional');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (14, 'Business Developer', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'PROFESSION', 'Business Developer');

--Insert Member type--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (15, 'MENTOR', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_TYPE', 'MENTOR');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (16, 'LEAD_MENTOR', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_TYPE', 'LEAD_MENTOR');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (17, 'PROTEGE', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_TYPE', 'PROTEGE');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (18, 'ADMIN', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_TYPE', 'ADMIN');

--Insert Member Role--
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (19, 'ADMINISTRATOR', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_ROLE', 'ADMINISTRATOR');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (20, 'SUPERVISOR', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_ROLE', 'SUPERVISOR');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (21, 'OPERATOR', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_ROLE', 'OPERATOR');
INSERT INTO USER_DEFINED_VALUES ( USER_DEFINED_VALUES_ID, USER_DEFINED_VALUES_DESCRIPTIO,RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,USER_DEFINED_VALUES_CATEGORY, USER_DEFINED_VALUES_VALUE ) VALUES (22, 'GUEST', '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:13:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'MEMBER_ROLE', 'GUEST');

INSERT INTO MEMBER_ROLE ( MEMBER_ROLE_ID, MEMBER_TYPE_ID ) VALUES (22, 15); 

--Start
INSERT INTO ITEM_VENDOR ( VENDOR_ID, VENDOR_NAME, VENDOR_EMAIL, VENDOR_ADDRESS, VENDOR_PHONE,
RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
2, 'DHL', 'dhl@yahoo.com', 'USA', 972, '1',  TO_Date( '09/13/2009 05:14:31 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:14:31 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO ITEM_VENDOR ( VENDOR_ID, VENDOR_NAME, VENDOR_EMAIL, VENDOR_ADDRESS, VENDOR_PHONE,
RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
3, 'ABC', 'abc@yahoo.com', 'Houston,USA', 972, '1',  TO_Date( '09/13/2009 05:17:19 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:17:20 AM', 'MM/DD/YYYY HH:MI:SS AM'));

INSERT INTO LOCAL_CHAPTER ( LOCAL_CHAPTER_ID, CHAPTER_LEAD_MEMBER_ID, LOCAL_CHAPTER_NAME,
LOCAL_CHAPTER_STREET_ADDRESS, LOCAL_CHAPTER_CITY, LOCAL_CHAPTER_STATE, LOCAL_CHAPTER_ZIP,
LOCAL_CHAPTER_EMAIL_ADDRESS, LOCAL_CHAPTER_URL, LOCAL_CHAPTER_PHONE, LOCAL_CHAPTER_FAX,
LOCAL_CHAPTER_COUNTRY, RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
1, NULL, 'Dallas Chapter', '101 Main Street', 'Richardson.', 'Texas', '75082', 'demo@yahoo.com'
, 'http://mail.google.com/', '972-111-2222', NULL, 'USA', '1',  TO_Date( '09/13/2009 04:35:52 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 04:39:44 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO LOCAL_CHAPTER ( LOCAL_CHAPTER_ID, CHAPTER_LEAD_MEMBER_ID, LOCAL_CHAPTER_NAME,
LOCAL_CHAPTER_STREET_ADDRESS, LOCAL_CHAPTER_CITY, LOCAL_CHAPTER_STATE, LOCAL_CHAPTER_ZIP,
LOCAL_CHAPTER_EMAIL_ADDRESS, LOCAL_CHAPTER_URL, LOCAL_CHAPTER_PHONE, LOCAL_CHAPTER_FAX,
LOCAL_CHAPTER_COUNTRY, RECORD_CREATOR_ID, RECORD_CREATED_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
2, NULL, 'Forth Worth Chapte', '102 Main Street', 'Fort Worth', 'Texas', '45453', 'mithun@yahoo.com'
, 'http://google.com', '972-111-2244', NULL, 'USA', '1',  TO_Date( '09/13/2009 04:40:18 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 04:40:18 AM', 'MM/DD/YYYY HH:MI:SS AM'));

INSERT INTO TEST_TUTORIAL_DOCUMENT ( TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO,
DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
3, 'English Document', NULL, NULL, '1',  TO_Date( '09/13/2009 05:30:58 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:30:58 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO TEST_TUTORIAL_DOCUMENT ( TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO,
DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
5, 'Second Chapter', NULL, NULL, '1',  TO_Date( '09/13/2009 05:32:48 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:32:48 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO TEST_TUTORIAL_DOCUMENT ( TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO,
DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
4, 'First Chapter', NULL, NULL, '1',  TO_Date( '09/13/2009 05:31:13 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:31:13 AM', 'MM/DD/YYYY HH:MI:SS AM'));

INSERT INTO TEST_TUTORIAL_MODULES ( TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID,
TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO,
MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
1, 3, 'Y', 1, 'Module -1', NULL, NULL, 'Module -1 Text', '1',  TO_Date( '09/13/2009 05:38:35 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:38:35 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO TEST_TUTORIAL_MODULES ( TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID,
TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO,
MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
3, 5, 'Y', 2, 'Second module', NULL, NULL, 'Second module Text', '1',  TO_Date( '09/13/2009 05:43:34 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:43:34 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO TEST_TUTORIAL_MODULES ( TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID,
TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO,
MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID,
RECORD_LAST_UPDATED_DATE ) VALUES ( 
4, 5, 'Y', 1, 'Third module', NULL, NULL, 'Third module text', '1',  TO_Date( '09/13/2009 05:44:12 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:44:12 AM', 'MM/DD/YYYY HH:MI:SS AM'));

INSERT INTO TRAINING_ITEM ( ITEM_ID, VENDOR_ID, ITEM_DESCRIPTION, ITEM_E_INDICATOR,
ITEM_SUBSCRIPTION_IND, ITEM_E_STORAGE_LOCATI, ITEM_PURCHASE_COST, ITEM_SALES_PRICE,
RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,
ITEM_VERSION, ITEM_LANGUAGE, ITEM_IMAGE, ITEM_AVAILABILITY ) VALUES ( 
2, 2, 'The Qur''an and the Arabic Language', 'Book', 'ERV009', 'SHV009', 20, 23, '1'
,  TO_Date( '09/13/2009 05:24:38 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:24:38 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1', 'English', NULL, 'Y'); 
INSERT INTO TRAINING_ITEM ( ITEM_ID, VENDOR_ID, ITEM_DESCRIPTION, ITEM_E_INDICATOR,
ITEM_SUBSCRIPTION_IND, ITEM_E_STORAGE_LOCATI, ITEM_PURCHASE_COST, ITEM_SALES_PRICE,
RECORD_CREATOR_ID, RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE,
ITEM_VERSION, ITEM_LANGUAGE, ITEM_IMAGE, ITEM_AVAILABILITY ) VALUES ( 
3, 3, 'Naat DVD, Awais Qadri, Owais Raza (Urdu) ', 'DVD', 'ERV009', 'SHV009', 20, 25
, '1',  TO_Date( '09/13/2009 05:25:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 05:25:45 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1', 'EN', NULL, 'N');

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE ) VALUES ( 
1, 1, 1, 'Quran 16:125 states that we should:', NULL, NULL, 'Quran 16:125 states that we should:'
, 'A', 'May avoid extremes in worship.', 'Assume leadership over non-Muslims.', ' Become the leader for both Muslims and non-Muslims.'
, 'Establish the Covenant of Madina. ', 'All of the above.', 'None of the above.'
, '1',  TO_Date( '09/13/2009 05:45:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), '1',  TO_Date( '09/13/2009 06:01:25 AM', 'MM/DD/YYYY HH:MI:SS AM'));

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE ) VALUES ( 
2, 1, 2, 'In inviting others to Islam, we should:', NULL, NULL, 'In inviting others to Islam, we should:'
, 'B', 'Use wisdom.', 'Preach in a beautiful manner.', 'Reason with them in the best possible ways. '
, 'Be gracious.', 'All of the above.', 'None of the above.', '1',  TO_Date( '09/13/2009 05:47:28 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:49:25 AM', 'MM/DD/YYYY HH:MI:SS AM')); 

INSERT INTO TEST_TUTORIAL_QUESTION_ANS ( TEST_TUTORIAL_QUESTION_ANS_ID, TEST_TUTORIAL_MODULES_ID,
PAGE_NUMBER, PAGE_TEXT, PAGE_AUDIO, PAGE_VIDEO, QUESTION, QUESTION_CORRECT_ANSWER,
QUESTION_OPTION_ANSWER_A, QUESTION_OPTION_ANSWER_B, QUESTION_OPTION_ANSWER_C,
QUESTION_OPTION_ANSWER_D, QUESTION_OPTION_ANSWER_E, QUESTION_OPTION_ANSWER_F, RECORD_CREATOR_ID,
RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE ) VALUES ( 
3, 3, 1, 'Many new converts to Islam face loss of: ', NULL, NULL, 'Many new converts to Islam face loss of: '
, 'C', 'Social support. ', 'Financial resources. ', 'Spiritual satisfaction. ', 'Vocational advancement. '
, 'All of the above. ', 'None of the above.', '1',  TO_Date( '09/13/2009 05:59:02 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '1',  TO_Date( '09/13/2009 05:59:02 AM', 'MM/DD/YYYY HH:MI:SS AM'));
