
Insert into TEST_TUTORIAL_DOCUMENT
   (TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO, DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME)
 Values
   (1, 'Mentor online tutorial', NULL, NULL, '1', 
    TO_DATE('09/13/2009 05:30:58', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('09/13/2009 05:30:58', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TEST_TUTORIAL_DOCUMENT
   (TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO, DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME)
 Values
   (2, 'Protégé online tutorial', NULL, NULL, '1', 
    TO_DATE('09/13/2009 05:32:48', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('09/13/2009 05:32:48', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TEST_TUTORIAL_DOCUMENT
   (TEST_TUTORIAL_DOCUMENT_ID, DOCUMENT_NAME, DOCUMENT_INTRO_AUDIO, DOCUMENT_INTRO_VIDEO, RECORD_CREATOR_ID, 
    RECORD_CREATE_DATE, RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME)
 Values
   (3, 'Online question and answer', NULL, NULL, '1', 
    TO_DATE('09/13/2009 05:31:13', 'MM/DD/YYYY HH24:MI:SS'), '1', TO_DATE('09/13/2009 05:31:13', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);


Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (1, 1, '1', 15, 'Module 1 - Da''wah Workshop', 
    NULL, NULL, '<p>Test</p>', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '19', TO_DATE('03/28/2010 18:36:10', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m1/m_1_page_1.swf', NULL, 'Da''wah Workshop', 
    1, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (2, 1, '1', 15, 'Module 2 - Challenges to Successful Da''wah', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m2/m_2_page_1.swf', NULL, 'Challenges to Successful Da''wah', 
    2, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (3, 1, '1', 15, 'Module 3 - Goals and Types of Da''wah', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m3/m_3_page_1.swf', NULL, 'Goals and Types of Da''wah', 
    3, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (4, 1, '1', 15, 'Module 4 - Da''wah As Marketing', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m4/m_4_page_1.swf', NULL, 'Da''wah As Marketing', 
    4, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (5, 1, '1', 15, 'Module 5 - The Art of Public Speaking', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m5/m_5_page_1.swf', NULL, 'The Art of Public Speaking', 
    5, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (9, 2, '0', 17, 'Islam 101', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m101/m_101_page_1.swf', NULL, 'Islam 101', 
    10, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (6, 1, '1', 15, 'Module 6A - Da''wah Content', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m6/m_6_page_1.swf', NULL, 'Da''wah Content', 
    6, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (10, 1, '1', 15, 'Module 6B - Da''wah Content', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m6b/m_6B_page_1.swf', NULL, 'Da''wah Content', 
    7, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (11, 1, '1', 15, 'Module 6C - Da''wah Content', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m6c/m_6B_page_1.swf', NULL, 'Da''wah Content', 
    8, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (7, 1, '1', 15, 'Module 7 - A Primer on Christianity for Muslims Engaged in Da''wah', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m7/m_7_page_1.swf', NULL, 'A Primer on Christianity for Muslims Engaged in Da''wah', 
    9, 10);
Insert into TEST_TUTORIAL_MODULES
   (TEST_TUTORIAL_MODULES_ID, TEST_TUTORIAL_DOCUMENT_ID, TEST_INDICATOR, MEMBER_TYPE_INDICATOR, MODULE_NAME, 
    MODULE_INTRO_AUDIO, MODULE_INTRO_VIDEO, MODULE_TEXT, RECORD_CREATOR_ID, RECORD_CREATE_DATE, 
    RECORD_LAST_UPDATER_ID, RECORD_LAST_UPDATED_DATE, AUDIO_FILE_NAME, VIDEO_FILE_NAME, MODULE_TITLE, 
    SERIAL, TEST_QUESTIONS_COUNT)
 Values
   (8, 1, '1', 15, 'Module 8 - Literature for Da''wah', 
    NULL, NULL, 'Test', '1', TO_DATE('09/13/2009 05:43:34', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('09/30/2009 23:09:34', 'MM/DD/YYYY HH24:MI:SS'), 'pages/secure/media/m8/m_8_page_1.swf', NULL, 'Literature for Da''wah', 
    9, 10);
COMMIT;

